# https://alacritty.org/config-alacritty.html
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 0, y = 0 }
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
opacity = 1

[colors]
transparent_background_colors = true

[font]
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
size = 14

[cursor]
style = { shape = "Block" }

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "-", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "0", mods = "Control|Shift", action = "ResetfontSize" },
  { key = "u", mods = "Control|Shift", action = "SearchBackward" },
]
